- name: setup mysql server
  hosts: dbsrv
  become: true
  tasks:
    - name: importing the db variable file
      include_vars: vars/db_setup

    - name: installing mysql server
      yum:
        name: mariadb-server
        state: present

    - name: install python mysql server
      yum:
        name: MySQL-python
        state: present


    - name: starting the mysql service
      service:
        name: mariadb
        state: started

    - name: creating the mysql database accounts
      mysql_db:
        name: "{{dbname}}"
        state: present
      register: db_out

    - name: creating ghe mysql database user
      mysql_user:
        name: "{{dbuser}}"
        password: "{{dbpass}}"
        priv: '*.*:ALL,GRANT'
        state: present
      register: dbuser_out


    - debug:
        var: db_out.db

    - debug:
        var: dbuser_out.user


